haml:
  enabled: true
  LineLength:
    enabled: false
ruby:
  enabled: true
  Style/StringLiteralsInInterpolation:
    Enabled: false
  Style/IfUnlessModifier:
    Description: Favor modifier if/unless usage when you have a single-line body.
    StyleGuide: https://github.com/bbatsov/ruby-style-guide#if-as-a-modifier
    Enabled: false
    MaxLineLength: 200