language: ruby
rvm:
  - 2.3.1
before_install:
  - export TZ='Europe/Moscow'
  - gem update --system
  - gem --version
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/application.yml.travis config/application.yml
  - bundle exec rake db:migrate RAILS_ENV=test